#+TITLE: TODO

* General
** TODO Figure out how to do runtime configuration
** DONE Data persistence layer of some kind
   CLOSED: [2020-02-14 Fri 02:24]
   :LOGBOOK:
   CLOCK: [2020-02-14 Fri 01:25]--[2020-02-14 Fri 02:23] =>  0:58
   :END:
+ sqlite?

I'm using [[https://diesel.rs][Diesel]] to do this. Let's see how this pans out.
** TODO Figure out why the nix build depends on all of the dependent crates
I thought rust was a compiled language. Might be weirdness due to using naersk
or it could be the panicinfo crud that plauged me in the webassembly work.
* Derpibooru
** TODO Image scraper
** TODO Search command
* E621
** DONE "safe" mode for not-NSFW channels
   CLOSED: [2020-02-15 Sat 03:47]
+ Append =rating:s= to the search terms?
+ Don't allow anything with higher than =rating:s= to be expanded?
** DONE cache messages somehow so that people have to react to them to find out more
   CLOSED: [2020-02-15 Sat 03:47]
*** Find out what it looks like to do reactions in serenity?
** TODO adapt to new e621 API
   :LOGBOOK:
   CLOCK: [2020-04-04 Sat 14:32]--[2020-04-04 Sat 16:10] =>  1:38
   :END:
* Voice
** TODO Some kind of crappy countdown thing for the racing people
